In [1]:
import sys  # module for python interpreter
sys.path.append('../')  # necessary for relative import of utils file e.g.

import os
import requests

import pandas as pd

from IPython.core.interactiveshell import InteractiveShell
# %load_ext autoreload
# %autoreload 2
# # %matplotlib inline
# %config IPCompleter.greedy=True

# pd.options.display.max_columns = None
# pd.options.display.max_rows = 200
# sns.set_palette("bright")
# sns.set(style="darkgrid")

InteractiveShell.ast_node_interactivity = "all"

# Load dataset

In [2]:
def download(url: str, dest_folder: str):
    if not os.path.exists(dest_folder):
        os.makedirs(dest_folder)  

    filename = url.split('/')[-1].replace(" ", "_")  
    file_path = os.path.join(dest_folder, filename)

    r = requests.get(url, stream=True)
    if r.ok:
        print("saving to", os.path.abspath(file_path))
        with open(file_path, 'wb') as f:
            for chunk in r.iter_content(chunk_size=1024 * 8):
                if chunk:
                    f.write(chunk)
                    f.flush()
                    os.fsync(f.fileno())
    else:  
        print("Download failed: status code {}\n{}".format(r.status_code, r.text))

In [3]:
url_to_titanic_data = 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv'

download(url_to_titanic_data,'./data')

saving to /Users/danieldeutsch/Desktop/code/pandas_transform_format/data/titanic.csv

# Transform data

In [5]:
df = pd.read_csv('./data/titanic.csv')
df.to_json(r'./data/titanic.json')

df.columns
df

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Siblings/Spouses Aboard',
       'Parents/Children Aboard', 'Fare'],
      dtype='object')

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [6]:
df = pd.read_json('./data/titanic.json')
df

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [10]:
df.to_hdf()

",Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare\n0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.25\n1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cumings,female,38.0,1,0,71.2833\n2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.925\n3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1\n4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.05\n5,0,3,Mr. James Moran,male,27.0,0,0,8.4583\n6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625\n7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.075\n8,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27.0,0,2,11.1333\n9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.0,1,0,30.0708\n10,1,3,Miss. Marguerite Rut Sandstrom,female,4.0,1,1,16.7\n11,1,1,Miss. Elizabeth Bonnell,female,58.0,0,0,26.55\n12,0,3,Mr. William Henry Saundercock,male,20.0,0,0,8.05\n13,0,3,Mr. Anders Johan Andersson,male,39.0,1,5,31.275\n14,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14.0,0,0,7.8542000000000005\n15,1,2,Mrs. (Mary D Kingcome) Hewlett,female,55.0,0,0,16.0\n16,0,3,Master. Eugene Rice,male,2.0,4,1,29.125\n17,1,2,Mr. Charles Eugene Williams,male,23.0,0,0,13.0\n18,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vander Planke,female,31.0,1,0,18.0\n19,1,3,Mrs. Fatima Masselmani,female,22.0,0,0,7.225\n20,0,2,Mr. Joseph J Fynney,male,35.0,0,0,26.0\n21,1,2,Mr. Lawrence Beesley,male,34.0,0,0,13.0\n22,1,3,Miss. Anna McGowan,female,15.0,0,0,8.0292\n23,1,1,Mr. William Thompson Sloper,male,28.0,0,0,35.5\n24,0,3,Miss. Torborg Danira Palsson,female,8.0,3,1,21.075\n25,1,3,Mrs. Carl Oscar (Selma Augusta Emilia Johansson) Asplund,female,38.0,1,5,31.3875\n26,0,3,Mr. Farred Chehab Emir,male,26.0,0,0,7.225\n27,0,1,Mr. Charles Alexander Fortune,male,19.0,3,2,263.0\n28,1,3,Miss. Ellen O'Dwyer,female,24.0,0,0,7.8792\n29,0,3,Mr. Lalio Todoroff,male,23.0,0,0,7.8958\n30,0,1,Don. Manuel E Uruchurtu,male,40.0,0,0,27.7208\n31,1,1,Mrs. William Augustus (Marie Eugenie) Spencer,female,48.0,1,0,146.5208\n32,1,3,Miss. Mary Agatha Glynn,female,18.0,0,0,7.75\n33,0,2,Mr. Edward H Wheadon,male,66.0,0,0,10.5\n34,0,1,Mr. Edgar Joseph Meyer,male,28.0,1,0,82.1708\n35,0,1,Mr. Alexander Oskar Holverson,male,42.0,1,0,52.0\n36,1,3,Mr. Hanna Mamee,male,18.0,0,0,7.2292\n37,0,3,Mr. Ernest Charles Cann,male,21.0,0,0,8.05\n38,0,3,Miss. Augusta Maria Vander Planke,female,18.0,2,0,18.0\n39,1,3,Miss. Jamila Nicola-Yarred,female,14.0,1,0,11.2417\n40,0,3,Mrs. Johan (Johanna Persdotter Larsson) Ahlin,female,40.0,1,0,9.475\n41,0,2,Mrs. William John Robert (Dorothy Ann Wonnacott) Turpin,female,27.0,1,0,21.0\n42,1,2,Miss. Simonne Marie Anne Andree Laroche,female,3.0,1,2,41.5792\n43,1,3,Miss. Margaret Delia Devaney,female,19.0,0,0,7.8792\n44,0,3,Mr. William John Rogers,male,30.0,0,0,8.05\n45,0,3,Mr. Denis Lennon,male,20.0,1,0,15.5\n46,1,3,Miss. Bridget O'Driscoll,female,27.0,0,0,7.75\n47,0,3,Mr. Youssef Samaan,male,16.0,2,0,21.6792\n48,0,3,Mrs. Josef (Josefine Franchi) Arnold-Franchi,female,18.0,1,0,17.8\n49,0,3,Master. Juha Niilo Panula,male,7.0,4,1,39.6875\n50,0,3,Mr. Richard Cater Nosworthy,male,21.0,0,0,7.8\n51,1,1,Mrs. Henry Sleeper (Myna Haxtun) Harper,female,49.0,1,0,76.7292\n52,1,2,Mrs. Lizzie (Elizabeth Anne Wilkinson) Faunthorpe,female,29.0,1,0,26.0\n53,0,1,Mr. Engelhart Cornelius Ostby,male,65.0,0,1,61.9792\n54,1,1,Mr. Hugh Woolner,male,46.0,0,0,35.5\n55,1,2,Miss. Emily Rugg,female,21.0,0,0,10.5\n56,0,3,Mr. Mansouer Novel,male,28.5,0,0,7.2292\n57,1,2,Miss. Constance Mirium West,female,5.0,1,2,27.75\n58,0,3,Master. William Frederick Goodwin,male,11.0,5,2,46.9\n59,0,3,Mr. Orsen Sirayanian,male,22.0,0,0,7.2292\n60,1,1,Miss. Amelie Icard,female,38.0,0,0,80.0\n61,0,1,Mr. Henry Birkhardt Harris,male,45.0,1,0,83.475\n62,0,3,Master. Harald Skoog,male,4.0,3,2,27.9\n63,0,1,Mr. Albert A Stewart,male,64.0,0,0,27.7208\n64,1,3,Master. Gerios Moubarek,male,7.0,1,1,15.2458\n65,1,2,Mrs. (Elizabeth Ramell) Nye,female,29.0,0,0,10.5\n66,0,3,Mr. Ernest James Crease,male,19.0,0,0,8.1583\n67,1,3,Miss. Erna Alexandra Andersson,female,17.0,4,2,7.925\n68,0,3,Mr. Vincenz Kink,male,26.0,2,0,8.6625\n69,0,2,Mr. Stephen Curnow Jenkin,male,32.0,0,0,10.5\n70,0,3,Miss. Lillian Amy Goodwin,female,16.0,5,2,46.9\n71,0,2,Mr. Ambrose Jr Hood,male,21.0,0,0,73.5\n72,0,3,Mr. Apostolos Chronopoulos,male,26.0,1,0,14.4542\n73,1,3,Mr. Lee Bing,male,32.0,0,0,56.4958\n74,0,3,Mr. Sigurd Hansen Moen,male,25.0,0,0,7.65\n75,0,3,Mr. Ivan Staneff,male,23.0,0,0,7.8958\n76,0,3,Mr. Rahamin Haim Moutal,male,28.0,0,0,8.05\n77,1,2,Master. Alden Gates Caldwell,male,0.8300000000000001,0,2,29.0\n78,1,3,Miss. Elizabeth Dowdell,female,30.0,0,0,12.475\n79,0,3,Mr. Achille Waelens,male,22.0,0,0,9.0\n80,1,3,Mr. Jan Baptist Sheerlinck,male,29.0,0,0,9.5\n81,1,3,Miss. Brigdet Delia McDermott,female,31.0,0,0,7.7875\n82,0,1,Mr. Francisco M Carrau,male,28.0,0,0,47.1\n83,1,2,Miss. Bertha Ilett,female,17.0,0,0,10.5\n84,1,3,Mrs. Karl Alfred (Maria Mathilda Gustafsson) Backstrom,female,33.0,3,0,15.85\n85,0,3,Mr. William Neal Ford,male,16.0,1,3,34.375\n86,0,3,Mr. Selman Francis Slocovski,male,20.0,0,0,8.05\n87,1,1,Miss. Mabel Helen Fortune,female,23.0,3,2,263.0\n88,0,3,Mr. Francesco Celotti,male,24.0,0,0,8.05\n89,0,3,Mr. Emil Christmann,male,29.0,0,0,8.05\n90,0,3,Mr. Paul Edvin Andreasson,male,20.0,0,0,7.8542000000000005\n91,0,1,Mr. Herbert Fuller Chaffee,male,46.0,1,0,61.175\n92,0,3,Mr. Bertram Frank Dean,male,26.0,1,2,20.575\n93,0,3,Mr. Daniel Coxon,male,59.0,0,0,7.25\n94,0,3,Mr. Charles Joseph Shorney,male,22.0,0,0,8.05\n95,0,1,Mr. George B Goldschmidt,male,71.0,0,0,34.6542\n96,1,1,Mr. William Bertram Greenfield,male,23.0,0,1,63.3583\n97,1,2,Mrs. John T (Ada Julia Bone) Doling,female,34.0,0,1,23.0\n98,0,2,Mr. Sinai Kantor,male,34.0,1,0,26.0\n99,0,3,Miss. Matilda Petranec,female,28.0,0,0,7.8958\n100,0,3,Mr. Pastcho Petroff,male,29.0,0,0,7.8958\n101,0,1,Mr. Richard Frasar White,male,21.0,0,1,77.2875\n102,0,3,Mr. Gustaf Joel Johansson,male,33.0,0,0,8.6542\n103,0,3,Mr. Anders Vilhelm Gustafsson,male,37.0,2,0,7.925\n104,0,3,Mr. Stoytcho Mionoff,male,28.0,0,0,7.8958\n105,1,3,Miss. Anna Kristine Salkjelsvik,female,21.0,0,0,7.65\n106,1,3,Mr. Albert Johan Moss,male,29.0,0,0,7.775\n107,0,3,Mr. Tido Rekic,male,38.0,0,0,7.8958\n108,1,3,Miss. Bertha Moran,female,28.0,1,0,24.15\n109,0,1,Mr. Walter Chamberlain Porter,male,47.0,0,0,52.0\n110,0,3,Miss. Hileni Zabour,female,14.5,1,0,14.4542\n111,0,3,Mr. David John Barton,male,22.0,0,0,8.05\n112,0,3,Miss. Katriina Jussila,female,20.0,1,0,9.825\n113,0,3,Miss. Malake Attalah,female,17.0,0,0,14.4583\n114,0,3,Mr. Edvard Pekoniemi,male,21.0,0,0,7.925\n115,0,3,Mr. Patrick Connors,male,70.5,0,0,7.75\n116,0,2,Mr. William John Robert Turpin,male,29.0,1,0,21.0\n117,0,1,Mr. Quigg Edmond Baxter,male,24.0,0,1,247.5208\n118,0,3,Miss. Ellis Anna Maria Andersson,female,2.0,4,2,31.275\n119,0,2,Mr. Stanley George Hickman,male,21.0,2,0,73.5\n120,0,3,Mr. Leonard Charles Moore,male,19.0,0,0,8.05\n121,0,2,Mr. Nicholas Nasser,male,32.5,1,0,30.0708\n122,1,2,Miss. Susan Webber,female,32.5,0,0,13.0\n123,0,1,Mr. Percival Wayland White,male,54.0,0,1,77.2875\n124,1,3,Master. Elias Nicola-Yarred,male,12.0,1,0,11.2417\n125,0,3,Mr. Martin McMahon,male,19.0,0,0,7.75\n126,1,3,Mr. Fridtjof Arne Madsen,male,24.0,0,0,7.1417\n127,1,3,Miss. Anna Peter,female,2.0,1,1,22.3583\n128,0,3,Mr. Johan Ekstrom,male,45.0,0,0,6.975\n129,0,3,Mr. Jozef Drazenoic,male,33.0,0,0,7.8958\n130,0,3,Mr. Domingos Fernandeo Coelho,male,20.0,0,0,7.05\n131,0,3,Mrs. Alexander A (Grace Charity Laury) Robins,female,47.0,1,0,14.5\n132,1,2,Mrs. Leopold (Mathilde Francoise Pede) Weisz,female,29.0,1,0,26.0\n133,0,2,Mr. Samuel James Hayden Sobey,male,25.0,0,0,13.0\n134,0,2,Mr. Emile Richard,male,23.0,0,0,15.0458\n135,1,1,Miss. Helen Monypeny Newsom,female,19.0,0,2,26.2833\n136,0,1,Mr. Jacques Heath Futrelle,male,37.0,1,0,53.1\n137,0,3,Mr. Olaf Elon Osen,male,16.0,0,0,9.2167\n138,0,1,Mr. Victor Giglio,male,24.0,0,0,79.2\n139,0,3,Mrs. Joseph (Sultana) Boulos,female,40.0,0,2,15.2458\n140,1,3,Miss. Anna Sofia Nysten,female,22.0,0,0,7.75\n141,1,3,Mrs. Pekka Pietari (Elin Matilda Dolck) Hakkarainen,female,24.0,1,0,15.85\n142,0,3,Mr. Jeremiah Burke,male,19.0,0,0,6.75\n143,0,2,Mr. Edgardo Samuel Andrew,male,18.0,0,0,11.5\n144,0,2,Mr. Joseph Charles Nicholls,male,19.0,1,1,36.75\n145,1,3,Mr. August Edvard Andersson,male,27.0,0,0,7.7958\n146,0,3,Miss. Robina Maggie Ford,female,9.0,2,2,34.375\n147,0,2,Mr. Michel Navratil,male,36.5,0,2,26.0\n148,0,2,Rev. Thomas Roussel Davids Byles,male,42.0,0,0,13.0\n149,0,2,Rev. Robert James Bateman,male,51.0,0,0,12.525\n150,1,1,Mrs. Thomas (Edith Wearne) Pears,female,22.0,1,0,66.6\n151,0,3,Mr. Alfonzo Meo,male,55.5,0,0,8.05\n152,0,3,Mr. Austin Blyler van Billiard,male,40.5,0,2,14.5\n153,0,3,Mr. Ole Martin Olsen,male,27.0,0,0,7.3125\n154,0,1,Mr. Charles Duane Williams,male,51.0,0,1,61.3792\n155,1,3,Miss. Katherine Gilnagh,female,16.0,0,0,7.7333\n156,0,3,Mr. Harry Corn,male,30.0,0,0,8.05\n157,0,3,Mr. Mile Smiljanic,male,37.0,0,0,8.6625\n158,0,3,Master. Thomas Henry Sage,male,5.0,8,2,69.55\n159,0,3,Mr. John Hatfield Cribb,male,44.0,0,1,16.1\n160,1,2,Mrs. James (Elizabeth Inglis Milne) Watt,female,40.0,0,0,15.75\n161,0,3,Mr. John Viktor Bengtsson,male,26.0,0,0,7.775\n162,0,3,Mr. Jovo Calic,male,17.0,0,0,8.6625\n163,0,3,Master. Eino Viljami Panula,male,1.0,4,1,39.6875\n164,1,3,Master. Frank John William Goldsmith,male,9.0,0,2,20.525\n165,1,1,Mrs. (Edith Martha Bowerman) Chibnall,female,48.0,0,1,55.0\n166,0,3,Mrs. William (Anna Bernhardina Karlsson) Skoog,female,45.0,1,4,27.9\n167,0,1,Mr. John D Baumann,male,60.0,0,0,25.925\n168,0,3,Mr. Lee Ling,male,28.0,0,0,56.4958\n169,0,1,Mr. Wyckoff Van der hoef,male,61.0,0,0,33.5\n170,0,3,Master. Arthur Rice,male,4.0,4,1,29.125\n171,1,3,Miss. Eleanor Ileen Johnson,female,1.0,1,1,11.1333\n172,0,3,Mr. Antti Wilhelm Sivola,male,21.0,0,0,7.925\n173,0,1,Mr. James Clinch Smith,male,56.0,0,0,30.6958\n174,0,3,Mr. Klas Albin Klasen,male,18.0,1,1,7.8542000000000005\n175,0,3,Master. Henry Forbes Lefebre,male,5.0,3,1,25.4667\n176,0,1,Miss. Ann Elizabeth Isham,female,50.0,0,0,28.7125\n177,0,2,Mr. Reginald Hale,male,30.0,0,0,13.0\n178,0,3,Mr. Lionel Leonard,male,36.0,0,0,0.0\n179,0,3,Miss. Constance Gladys Sage,female,8.0,8,2,69.55\n180,0,2,Mr. Rene Pernot,male,39.0,0,0,15.05\n181,0,3,Master. Clarence Gustaf Hugo Asplund,male,9.0,4,2,31.3875\n182,1,2,Master. Richard F Becker,male,1.0,2,1,39.0\n183,1,3,Miss. Luise Gretchen Kink-Heilmann,female,4.0,0,2,22.025\n184,0,1,Mr. Hugh Roscoe Rood,male,39.0,0,0,50.0\n185,1,3,Mrs. Thomas (Johanna Godfrey) O'Brien,female,26.0,1,0,15.5\n186,1,1,Mr. Charles Hallace Romaine,male,45.0,0,0,26.55\n187,0,3,Mr. John Bourke,male,40.0,1,1,15.5\n188,0,3,Mr. Stjepan Turcin,male,36.0,0,0,7.8958\n189,1,2,Mrs. (Rosa) Pinsky,female,32.0,0,0,13.0\n190,0,2,Mr. William Carbines,male,19.0,0,0,13.0\n191,1,3,Miss. Carla Christine Nielsine Andersen-Jensen,female,19.0,1,0,7.8542000000000005\n192,1,2,Master. Michel M Navratil,male,3.0,1,1,26.0\n193,1,1,Mrs. James Joseph (Margaret Tobin) Brown,female,44.0,0,0,27.7208\n194,1,1,Miss. Elise Lurette,female,58.0,0,0,146.5208\n195,0,3,Mr. Robert Mernagh,male,28.0,0,0,7.75\n196,0,3,Mr. Karl Siegwart Andreas Olsen,male,42.0,0,1,8.4042\n197,1,3,Miss. Margaret Madigan,female,21.0,0,0,7.75\n198,0,2,Miss. Henriette Yrois,female,24.0,0,0,13.0\n199,0,3,Mr. Nestor Cyriel Vande Walle,male,28.0,0,0,9.5\n200,0,3,Mr. Frederick Sage,male,17.0,8,2,69.55\n201,0,3,Mr. Jakob Alfred Johanson,male,34.0,0,0,6.4958\n202,0,3,Mr. Gerious Youseff,male,45.5,0,0,7.225\n203,1,3,Mr. Gurshon Cohen,male,18.0,0,0,8.05\n204,0,3,Miss. Telma Matilda Strom,female,2.0,0,1,10.4625\n205,0,3,Mr. Karl Alfred Backstrom,male,32.0,1,0,15.85\n206,1,3,Mr. Nassef Cassem Albimona,male,26.0,0,0,18.7875\n207,1,3,Miss. Helen Carr,female,16.0,0,0,7.75\n208,1,1,Mr. Henry Blank,male,40.0,0,0,31.0\n209,0,3,Mr. Ahmed Ali,male,24.0,0,0,7.05\n210,1,2,Miss. Clear Annie Cameron,female,35.0,0,0,21.0\n211,0,3,Mr. John Henry Perkin,male,22.0,0,0,7.25\n212,0,2,Mr. Hans Kristensen Givard,male,30.0,0,0,13.0\n213,0,3,Mr. Philip Kiernan,male,22.0,1,0,7.75\n214,1,1,Miss. Madeleine Newell,female,31.0,1,0,113.275\n215,1,3,Miss. Eliina Honkanen,female,27.0,0,0,7.925\n216,0,2,Mr. Sidney Samuel Jacobsohn,male,42.0,1,0,27.0\n217,1,1,Miss. Albina Bazzani,female,32.0,0,0,76.2917\n218,0,2,Mr. Walter Harris,male,30.0,0,0,10.5\n219,1,3,Mr. Victor Francis Sunderland,male,16.0,0,0,8.05\n220,0,2,Mr. James H Bracken,male,27.0,0,0,13.0\n221,0,3,Mr. George Henry Green,male,51.0,0,0,8.05\n222,0,3,Mr. Christo Nenkoff,male,22.0,0,0,7.8958\n223,1,1,Mr. Frederick Maxfield Hoyt,male,38.0,1,0,90.0\n224,0,3,Mr. Karl Ivar Sven Berglund,male,22.0,0,0,9.35\n225,1,2,Mr. William John Mellors,male,19.0,0,0,10.5\n226,0,3,Mr. John Hall Lovell,male,20.5,0,0,7.25\n227,0,2,Mr. Arne Jonas Fahlstrom,male,18.0,0,0,13.0\n228,0,3,Miss. Mathilde Lefebre,female,12.0,3,1,25.4667\n229,1,1,Mrs. Henry Birkhardt (Irene Wallach) Harris,female,35.0,1,0,83.475\n230,0,3,Mr. Bengt Edvin Larsson,male,29.0,0,0,7.775\n231,0,2,Mr. Ernst Adolf Sjostedt,male,59.0,0,0,13.5\n232,1,3,Miss. Lillian Gertrud Asplund,female,5.0,4,2,31.3875\n233,0,2,Mr. Robert William Norman Leyson,male,24.0,0,0,10.5\n234,0,3,Miss. Alice Phoebe Harknett,female,21.0,0,0,7.55\n235,0,2,Mr. Stephen Hold,male,44.0,1,0,26.0\n236,1,2,Miss. Marjorie Collyer,female,8.0,0,2,26.25\n237,0,2,Mr. Frederick William Pengelly,male,19.0,0,0,10.5\n238,0,2,Mr. George Henry Hunt,male,33.0,0,0,12.275\n239,0,3,Miss. Thamine Zabour,female,19.0,1,0,14.4542\n240,1,3,Miss. Katherine Murphy,female,18.0,1,0,15.5\n241,0,2,Mr. Reginald Charles Coleridge,male,29.0,0,0,10.5\n242,0,3,Mr. Matti Alexanteri Maenpaa,male,22.0,0,0,7.125\n243,0,3,Mr. Sleiman Attalah,male,30.0,0,0,7.225\n244,0,1,Dr. William Edward Minahan,male,44.0,2,0,90.0\n245,0,3,Miss. Agda Thorilda Viktoria Lindahl,female,25.0,0,0,7.775\n246,1,2,Mrs. William (Anna) Hamalainen,female,24.0,0,2,14.5\n247,1,1,Mr. Richard Leonard Beckwith,male,37.0,1,1,52.5542\n248,0,2,Rev. Ernest Courtenay Carter,male,54.0,1,0,26.0\n249,0,3,Mr. James George Reed,male,18.0,0,0,7.25\n250,0,3,Mrs. Wilhelm (Elna Matilda Persson) Strom,female,29.0,1,1,10.4625\n251,0,1,Mr. William Thomas Stead,male,62.0,0,0,26.55\n252,0,3,Mr. William Arthur Lobb,male,30.0,1,0,16.1\n253,0,3,Mrs. Viktor (Helena Wilhelmina) Rosblom,female,41.0,0,2,20.2125\n254,1,3,Mrs. Darwis (Hanne Youssef Razi) Touma,female,29.0,0,2,15.2458\n255,1,1,Mrs. Gertrude Maybelle Thorne,female,38.0,0,0,79.2\n256,1,1,Miss. Gladys Cherry,female,30.0,0,0,86.5\n257,1,1,Miss. Anna Ward,female,35.0,0,0,512.3292\n258,1,2,Mrs. (Lutie Davis) Parrish,female,50.0,0,1,26.0\n259,1,3,Master. Edvin Rojj Felix Asplund,male,3.0,4,2,31.3875\n260,0,1,Mr. Emil Taussig,male,52.0,1,1,79.65\n261,0,1,Mr. William Harrison,male,40.0,0,0,0.0\n262,0,3,Miss. Delia Henry,female,21.0,0,0,7.75\n263,0,2,Mr. David Reeves,male,36.0,0,0,10.5\n264,0,3,Mr. Ernesti Arvid Panula,male,16.0,4,1,39.6875\n265,1,3,Mr. Ernst Ulrik Persson,male,25.0,1,0,7.775\n266,1,1,Mrs. William Thompson (Edith Junkins) Graham,female,58.0,0,1,153.4625\n267,1,1,Miss. Amelia Bissette,female,35.0,0,0,135.6333\n268,0,1,Mr. Alexander Cairns,male,28.0,0,0,31.0\n269,1,3,Mr. William Henry Tornquist,male,25.0,0,0,0.0\n270,1,2,Mrs. (Elizabeth Anne Maidment) Mellinger,female,41.0,0,1,19.5\n271,0,1,Mr. Charles H Natsch,male,37.0,0,1,29.7\n272,1,3,Miss. Hanora Healy,female,33.0,0,0,7.75\n273,1,1,Miss. Kornelia Theodosia Andrews,female,63.0,1,0,77.9583\n274,0,3,Miss. Augusta Charlotta Lindblom,female,45.0,0,0,7.75\n275,0,2,Mr. Francis Parkes,male,21.0,0,0,0.0\n276,0,3,Master. Eric Rice,male,7.0,4,1,29.125\n277,1,3,Mrs. Stanton (Rosa Hunt) Abbott,female,35.0,1,1,20.25\n278,0,3,Mr. Frank Duane,male,65.0,0,0,7.75\n279,0,3,Mr. Nils Johan Goransson Olsson,male,28.0,0,0,7.8542000000000005\n280,0,3,Mr. Alfons de Pelsmaeker,male,16.0,0,0,9.5\n281,1,3,Mr. Edward Arthur Dorking,male,19.0,0,0,8.05\n282,0,1,Mr. Richard William Smith,male,57.0,0,0,26.0\n283,0,3,Mr. Ivan Stankovic,male,33.0,0,0,8.6625\n284,1,3,Mr. Theodore de Mulder,male,30.0,0,0,9.5\n285,0,3,Mr. Penko Naidenoff,male,22.0,0,0,7.8958\n286,1,2,Mr. Masabumi Hosono,male,42.0,0,0,13.0\n287,1,3,Miss. Kate Connolly,female,22.0,0,0,7.75\n288,1,1,Miss. Ellen Barber,female,26.0,0,0,78.85\n289,1,1,Mrs. Dickinson H (Helen Walton) Bishop,female,19.0,1,0,91.0792\n290,0,2,Mr. Rene Jacques Levy,male,36.0,0,0,12.875\n291,0,3,Miss. Aloisia Haas,female,24.0,0,0,8.85\n292,0,3,Mr. Ivan Mineff,male,24.0,0,0,7.8958\n293,0,1,Mr. Ervin G Lewy,male,30.0,0,0,27.7208\n294,0,3,Mr. Mansour Hanna,male,23.5,0,0,7.2292\n295,0,1,Miss. Helen Loraine Allison,female,2.0,1,2,151.55\n296,1,1,Mr. Adolphe Saalfeld,male,47.0,0,0,30.5\n297,1,1,Mrs. James (Helene DeLaudeniere Chaput) Baxter,female,50.0,0,1,247.5208\n298,1,3,Miss. Anna Katherine Kelly,female,20.0,0,0,7.75\n299,1,3,Mr. Bernard McCoy,male,24.0,2,0,23.25\n300,0,3,Mr. William Cahoone Jr Johnson,male,19.0,0,0,0.0\n301,1,2,Miss. Nora A Keane,female,46.0,0,0,12.35\n302,0,3,Mr. Howard Hugh Williams,male,28.0,0,0,8.05\n303,1,1,Master. Hudson Trevor Allison,male,0.92,1,2,151.55\n304,1,1,Miss. Margaret Fleming,female,42.0,0,0,110.8833\n305,1,1,Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo) Penasco y Castellana,female,17.0,1,0,108.9\n306,0,2,Mr. Samuel Abelson,male,30.0,1,0,24.0\n307,1,1,Miss. Laura Mabel Francatelli,female,30.0,0,0,56.9292\n308,1,1,Miss. Margaret Bechstein Hays,female,24.0,0,0,83.1583\n309,1,1,Miss. Emily Borie Ryerson,female,18.0,2,2,262.375\n310,0,2,Mrs. William (Anna Sylfven) Lahtinen,female,26.0,1,1,26.0\n311,0,3,Mr. Ignjac Hendekovic,male,28.0,0,0,7.8958\n312,0,2,Mr. Benjamin Hart,male,43.0,1,1,26.25\n313,1,3,Miss. Helmina Josefina Nilsson,female,26.0,0,0,7.8542000000000005\n314,1,2,Mrs. Sinai (Miriam Sternin) Kantor,female,24.0,1,0,26.0\n315,0,2,Dr. Ernest Moraweck,male,54.0,0,0,14.0\n316,1,1,Miss. Mary Natalie Wick,female,31.0,0,2,164.8667\n317,1,1,Mrs. Frederic Oakley (Margaretta Corning Stone) Spedden,female,40.0,1,1,134.5\n318,0,3,Mr. Samuel Dennis,male,22.0,0,0,7.25\n319,0,3,Mr. Yoto Danoff,male,27.0,0,0,7.8958\n320,1,2,Miss. Hilda Mary Slayter,female,30.0,0,0,12.35\n321,1,2,Mrs. Albert Francis (Sylvia Mae Harbaugh) Caldwell,female,22.0,1,1,29.0\n322,0,3,Mr. George John Jr Sage,male,20.0,8,2,69.55\n323,1,1,Miss. Marie Grice Young,female,36.0,0,0,135.6333\n324,0,3,Mr. Johan Hansen Nysveen,male,61.0,0,0,6.2375\n325,1,2,Mrs. (Ada E Hall) Ball,female,36.0,0,0,13.0\n326,1,3,Mrs. Frank John (Emily Alice Brown) Goldsmith,female,31.0,1,1,20.525\n327,1,1,Miss. Jean Gertrude Hippach,female,16.0,0,1,57.9792\n328,1,3,Miss. Agnes McCoy,female,28.0,2,0,23.25\n329,0,1,Mr. Austen Partner,male,45.5,0,0,28.5\n330,0,1,Mr. George Edward Graham,male,38.0,0,1,153.4625\n331,0,3,Mr. Leo Edmondus Vander Planke,male,16.0,2,0,18.0\n332,1,1,Mrs. Henry William (Clara Heinsheimer) Frauenthal,female,42.0,1,0,133.65\n333,0,3,Mr. Mitto Denkoff,male,30.0,0,0,7.8958\n334,0,1,Mr. Thomas Clinton Pears,male,29.0,1,0,66.6\n335,1,1,Miss. Elizabeth Margaret Burns,female,41.0,0,0,134.5\n336,1,3,Mr. Karl Edwart Dahl,male,45.0,0,0,8.05\n337,0,1,Mr. Stephen Weart Blackwell,male,45.0,0,0,35.5\n338,1,2,Master. Edmond Roger Navratil,male,2.0,1,1,26.0\n339,1,1,Miss. Alice Elizabeth Fortune,female,24.0,3,2,263.0\n340,0,2,Mr. Erik Gustaf Collander,male,28.0,0,0,13.0\n341,0,2,Mr. Charles Frederick Waddington Sedgwick,male,25.0,0,0,13.0\n342,0,2,Mr. Stanley Hubert Fox,male,36.0,0,0,13.0\n343,1,2,Miss. Amelia Brown,female,24.0,0,0,13.0\n344,1,2,Miss. Marion Elsie Smith,female,40.0,0,0,13.0\n345,1,3,Mrs. Thomas Henry (Mary E Finck) Davison,female,34.0,1,0,16.1\n346,1,3,Master. William Loch Coutts,male,3.0,1,1,15.9\n347,0,3,Mr. Jovan Dimic,male,42.0,0,0,8.6625\n348,0,3,Mr. Nils Martin Odahl,male,23.0,0,0,9.225\n349,0,1,Mr. Fletcher Fellows Williams-Lambert,male,43.0,0,0,35.0\n350,0,3,Mr. Tannous Elias,male,15.0,1,1,7.2292\n351,0,3,Mr. Josef Arnold-Franchi,male,25.0,1,0,17.8\n352,0,3,Mr. Wazli Yousif,male,23.0,0,0,7.225\n353,0,3,Mr. Leo Peter Vanden Steen,male,28.0,0,0,9.5\n354,1,1,Miss. Elsie Edith Bowerman,female,

In [13]:


df.to_hdf(
    './titanic_data.h5',
    'titanic_data',
    mode='w')

In [16]:
pd.read_hdf('./titanic_data.h5')

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500